export enum AuthException {
    BAD_TOKEN = 'BAD_TOKEN',
    BAD_REFRESH_TOKEN = 'BAD_REFRESH_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    UNAUTHORIZED = 'UNAUTHORIZED',
    PERMISSION_DENY = 'PERMISSION_DENY',
    INVALID_LOGIN_CREDENTIALS = 'INVALID_LOGIN_CREDENTIALS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_EXIST = 'EMAIL_EXIST',
    CUSTOM = 'CUSTOM',
}
