/** Declaration file generated by dts-gen */

export = ajv_keywords;

declare function ajv_keywords(ajv: any, keyword: any): any;

declare namespace ajv_keywords {
    const prototype: {
    };

    function get(keyword: any): any;

    namespace get {
        const prototype: {
        };
    }

}

