export enum AppExceptionType {
  QUERY_FAIL = 'QUERY_FAIL',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  CUSTOM = 'CUSTOM',
  INVALID_SCOPE = 'INVALID_SCOPE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNEXPECTED = 'UNEXPECTED',
  BAD_REQUEST = 'BAD_REQUEST',
}
